version: '3'
services:
  app:
    build:
      context: .
      target: ${TARGET:-dev}
    working_dir: /app
    volumes:
      - ${PWD:-./}:/${TARGET:-app}
    ports:
      - "8083:8083"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mariadb:10.9.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    command: sh -c 'echo "[client]\nuser=root\npassword=${DB_PASSWORD}" > /root/.my.cnf && docker-entrypoint.sh mysqld'
    volumes:
      - "${PWD:-./}:/app"
      - "dbdata:/var/lib/mysql"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  maildev:
    image: maildev/maildev
    ports:
      - "8025:1080"

volumes:
  dbdata:
